[package]
name = "query-router"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "query-router"
path = "src/main.rs"

[dependencies]
# Workspace
rpc         = { path = "../rpc" }
utils       = { path = "../utils/" }

# Crates.io
log         = "0.4"
env_logger  = "0.8"
warp        = "0.2"
anyhow      = "1.0"
lru-cache   = "0.1"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
structopt   = "0.3"
uuid        = { version = "0.8", features = ["v1", "serde"] }
tokio       = { version = "1", features = ["macros", "rt-multi-thread"] }
