# syntax=docker/dockerfile:experimental
FROM local/cache
RUN --mount=type=cache,mode=0755,target=/usr/src/cdl/target \
    --mount=type=cache,mode=0755,target=/root/.cargo/registry \
    tar xfz cache_target.tar.gz -C /usr/src/cdl/target && \
    tar xfz cache_registry.tar.gz -C /root/.cargo/registry

