# syntax=docker/dockerfile:experimental
FROM alpine as cache-export
RUN --mount=type=cache,mode=0755,target=/usr/src/cdl/target \
    --mount=type=cache,mode=0755,target=/root/.cargo/registry \
    tar cfz cache_target.tar.gz -C /usr/src/cdl/target . && \
    tar cfz cache_registry.tar.gz -C /root/.cargo/registry .
