[package]
name = "api"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "api"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace
rpc         = { path = "../rpc" }
utils       = { path = "../utils" }

# Crates.io
anyhow      = "1.0"
env_logger  = "0.8"
futures     = "0.3"
juniper     = { version = "0.15", features = ["uuid"] }
log         = "0.4"
num-derive  = "0.3.3"
num-traits  = "0.2.14"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0.61"
structopt   = "0.3"
thiserror   = "1.0"
tokio       = { version = "1", features = ["sync", "rt-multi-thread", "macros"] }
uuid        = { version = "0.8", features = ["v4", "serde"] }
warp        = "0.2"
async-stream            = "0.3"
juniper_graphql_ws      = "0.2"
juniper_warp            = { version = "0.6", features = ["subscriptions"] }
